# Generated by Django 4.1.4 on 2023-11-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expo', '0003_delete_performadoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PortName', models.CharField(max_length=100)),
                ('CountryName', models.CharField(max_length=100)),
            ],
        ),
    ]
