# Generated by Django 4.1.4 on 2023-11-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0006_shipmentterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentname', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=500)),
            ],
        ),
    ]
