# Generated by Django 4.1.4 on 2023-11-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0008_material_packages_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performa',
            fields=[
                ('Pino', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Buyerorder', models.CharField(max_length=256)),
                ('Orderdate', models.DateTimeField()),
                ('Consignee', models.CharField(max_length=256)),
                ('Country', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('PortName', models.CharField(max_length=100)),
                ('PreCarriage', models.CharField(max_length=256)),
                ('Vessel', models.CharField(max_length=256)),
                ('ReceiptCarrier', models.CharField(max_length=256)),
                ('SalesBroker', models.CharField(max_length=256)),
                ('Currency', models.CharField(max_length=30)),
                ('CountryLoad', models.CharField(max_length=30)),
                ('CountryDis', models.CharField(max_length=30)),
                ('Conversion', models.DecimalField(decimal_places=4, max_digits=8)),
                ('Bank', models.CharField(max_length=256)),
                ('DocumentName', models.CharField(max_length=100)),
                ('ShipmentPeriod', models.CharField(max_length=100)),
                ('shipmentname', models.CharField(max_length=100)),
                ('paymentname', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('packagename', models.CharField(max_length=100)),
                ('materialname', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Totalprice', models.FloatField()),
                ('Unit', models.CharField(max_length=100)),
                ('NetWeight', models.FloatField()),
                ('GrossWeight', models.FloatField()),
                ('Packagetype', models.CharField(max_length=100)),
                ('QualitySpecification', models.CharField(max_length=100)),
            ],
        ),
    ]
