# Generated by Django 4.0.5 on 2023-11-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0009_performa'),
    ]

    operations = [
        migrations.AddField(
            model_name='performa',
            name='Buyername',
            field=models.CharField(default='unknown', max_length=256),
        ),
        migrations.AddField(
            model_name='performa',
            name='Notify',
            field=models.CharField(default='unknown', max_length=256),
        ),
    ]
