# Generated by Django 4.0.5 on 2023-11-09 11:49

from django.db import migrations, models
import expo.ConsigneeModal


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0010_performa_buyername_performa_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('ConId', expo.ConsigneeModal.CustomConsigneeKey(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Con_Name', models.CharField(max_length=150)),
            ],
        ),
    ]
