# Generated by Django 4.0.5 on 2023-11-15 08:23

from django.db import migrations, models
import expo.BuyernameModal


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0011_consignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyername',
            fields=[
                ('BuyId', expo.BuyernameModal.CustomeBuyerKey(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Buyer_name', models.CharField(max_length=150)),
            ],
        ),
    ]
