# Generated by Django 4.0.5 on 2023-11-15 11:33

from django.db import migrations, models
import expo.NotifyModal


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0012_buyername'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyName',
            fields=[
                ('NotiKey', expo.NotifyModal.CustomeNotifykey(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Notify_name', models.CharField(max_length=150)),
            ],
        ),
    ]
