# Generated by Django 4.0.5 on 2023-12-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0015_purchaseorderdoc_alter_performa_buyername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderdoc',
            name='packaging',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='purchaseorderdoc',
            name='shipmentdate',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
