# Generated by Django 4.0.5 on 2023-12-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0016_purchaseorderdoc_packaging_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorformaDocument',
            fields=[
                ('porforno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('porfordate', models.DateField(blank=True, null=True)),
                ('purno', models.CharField(max_length=100)),
                ('ponodate', models.DateField(blank=True, null=True)),
                ('custname', models.CharField(max_length=256)),
                ('custadd', models.CharField(max_length=256)),
                ('custbank', models.CharField(max_length=256)),
                ('custcountry', models.CharField(max_length=256)),
                ('Consignee', models.CharField(max_length=256)),
                ('Notify', models.CharField(max_length=256)),
                ('currency', models.CharField(max_length=256)),
                ('product', models.CharField(max_length=256)),
                ('quantity', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=256)),
                ('rate', models.CharField(max_length=256)),
                ('rateunit', models.CharField(max_length=256)),
                ('shipmentterm', models.CharField(max_length=256)),
                ('paymentterm', models.CharField(max_length=256)),
                ('totalbag', models.IntegerField()),
                ('documents', models.CharField(max_length=256)),
                ('countryload', models.CharField(max_length=256)),
                ('countrydis', models.CharField(max_length=256)),
                ('portload', models.CharField(max_length=256)),
                ('portdis', models.CharField(max_length=256)),
                ('shipmentdate', models.CharField(blank=True, max_length=256)),
                ('packaging', models.CharField(blank=True, max_length=256)),
                ('NetWeight', models.FloatField()),
                ('GrossWeight', models.FloatField()),
                ('PreCarriage', models.CharField(max_length=256)),
                ('SalesBroker', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Performa',
        ),
    ]
