# Generated by Django 4.0.5 on 2023-12-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0019_porformadocument_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('invociedate', models.DateField(blank=True, null=True)),
                ('porforno', models.CharField(max_length=100)),
                ('porfordate', models.DateField(blank=True, null=True)),
                ('purno', models.CharField(max_length=100)),
                ('ponodate', models.DateField(blank=True, null=True)),
                ('custname', models.CharField(max_length=256)),
                ('custadd', models.CharField(max_length=256)),
                ('custbank', models.CharField(max_length=256)),
                ('custcountry', models.CharField(max_length=256)),
                ('Consignee', models.CharField(max_length=256)),
                ('Notify', models.CharField(max_length=256)),
                ('currency', models.CharField(max_length=256)),
                ('product', models.CharField(max_length=256)),
                ('quantity', models.CharField(max_length=256)),
                ('unit', models.CharField(max_length=256)),
                ('rate', models.CharField(max_length=256)),
                ('rateunit', models.CharField(max_length=256)),
                ('shipmentterm', models.CharField(max_length=256)),
                ('paymentterm', models.CharField(max_length=256)),
                ('totalbag', models.IntegerField()),
                ('documents', models.CharField(max_length=256)),
                ('countryload', models.CharField(max_length=256)),
                ('countrydis', models.CharField(max_length=256)),
                ('portload', models.CharField(max_length=256)),
                ('portdis', models.CharField(max_length=256)),
                ('shipmentdate', models.CharField(blank=True, max_length=256)),
                ('packaging', models.CharField(blank=True, max_length=256)),
                ('NetWeight', models.FloatField()),
                ('GrossWeight', models.FloatField()),
                ('PreCarriage', models.CharField(max_length=256)),
                ('SalesBroker', models.CharField(max_length=256)),
                ('Amount', models.FloatField(blank=True)),
                ('container', models.CharField(max_length=256)),
                ('csseal', models.CharField(max_length=256)),
                ('sb', models.CharField(max_length=256)),
                ('bl', models.CharField(max_length=256)),
                ('advamount', models.CharField(max_length=256)),
                ('remaamount', models.IntegerField()),
            ],
        ),
    ]
